# fly.toml app configuration file generated for lavatools-web on 2025-08-14T11:17:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lavatools-web'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"
  [build.args]
    VITE_API_URL = "https://lavatools-api.fly.dev"
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
